version: '3'

services:
  web:
    restart: always
    build:
      context: .
    ports:
      - '8008:8000'
    env_file:
      - local-var.env
    volumes:
      - "./src:/src"
    environment:
      DEBUG: 'true'
    # command precisa ser atualizado
    command: /usr/local/bin/gunicorn supersite.wsgi:application -w 2 -b :8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8888:80"
    volumes:
      - "./src/statifiles:/www/static"
    links:
      - web:web