version: '3'

services:
  web:
    restart: always
    build: ./src
    expose:
      - '8000'
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/usr/src/app1
      - web-static:/usr/src/app1/static
    env_file: .env-vars
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn my_project.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:11.6-alpine
    #POSTGRES_VERSION=11.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
